name: Deploy to Production

on:
  push:
    branches: [main, ci-cd]

jobs:
  checks:
    uses: ./.github/workflows/common-checks.yml

  deploy:
    needs: checks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Vercel CLI
        run: npm install -g vercel

      - name: Deploy to Vercel
        run: vercel deploy --prod --token=${{ secrets.VERCEL_TOKEN }}
        env:
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

      - name: Notify Telegram
        run: |
          curl -s -X POST https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/sendMessage \
          -d chat_id=${{ secrets.TELEGRAM_CHAT_ID }} \
          -d text="✅ Production Deployed: ${{ github.sha }}"

      - name: Notify WhatsApp (via Twilio)
        run: |
          curl -X POST https://api.twilio.com/2010-04-01/Accounts/${{ secrets.TWILIO_ACCOUNT_SID }}/Messages.json \
          --data-urlencode "From=whatsapp:${{ secrets.TWILIO_WHATSAPP_FROM }}" \
          --data-urlencode "To=whatsapp:${{ secrets.TWILIO_WHATSAPP_TO }}" \
          --data-urlencode "Body=✅ Prod deployed: ${{ github.sha }}" \
          -u ${{ secrets.TWILIO_ACCOUNT_SID }}:${{ secrets.TWILIO_AUTH_TOKEN }}

  rollback:
    if: failure()
    needs: deploy
    uses: ./.github/workflows/rollback.yml
