name: Release

on:
  push:
    # branches: [main]
    branches: [ci-cd]

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: googleapis/release-please-action@v4
        with:
          token: ${{ secrets.RELEASE_PLEASE_PAT }}
          config-file: .github/config/release-please-config.json
          manifest-file: .github/config/.release-please-manifest.json
