name: Release

on:
  push:
    # branches: [main]
    branches: [ci-cd]

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: googleapis/release-please-action@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          default-branch: ci-cd
