name: Rollback Production

on:
  workflow_call:

jobs:
  rollback:
    runs-on: ubuntu-latest
    steps:
      - name: Rollback to last good build
        run: vercel rollback --token=${{ secrets.VERCEL_TOKEN }}

      - name: Notify Telegram
        run: |
          curl -s -X POST https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/sendMessage \
          -d chat_id=${{ secrets.TELEGRAM_CHAT_ID }} \
          -d text="⚠️ Rollback triggered due to failure. Restored to last known good deployment."

      - name: Notify WhatsApp
        run: |
          curl -X POST https://api.twilio.com/2010-04-01/Accounts/${{ secrets.TWILIO_ACCOUNT_SID }}/Messages.json \
          --data-urlencode "From=whatsapp:${{ secrets.TWILIO_WHATSAPP_FROM }}" \
          --data-urlencode "To=whatsapp:${{ secrets.TWILIO_WHATSAPP_TO }}" \
          --data-urlencode "Body=⚠️ Rollback triggered after deployment failure." \
          -u ${{ secrets.TWILIO_ACCOUNT_SID }}:${{ secrets.TWILIO_AUTH_TOKEN }}
